### ISSUE TITLE
Canceling Account doesn't require password

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera-todo#151]
I tried to delete a test account and I did so without using the password. Also, when I deleted the account the email is still in use. I want to remove that email so I can use ryanadanderson@gmail.com on the account that is currently ryan.adanderson@gmail.com so I wont forget it :-P

**Comment by NullVoxPopuli** [comment]
makse sense. I'll fix that for ya when I get home. :-)

**Comment by NullVoxPopuli** [comment]
do you mean you want to delete an event, and then change your email?

**Comment by ryanadanderson** [comment]
Purge my existing ryanadanderson email so I can use it with my
Ryan.adanderson@gmail.com. :-)  The whistle stop is something I want to
keep of possible. It should be linked with the correct account.

**Comment by NullVoxPopuli** [comment]
if you login, click the gear in the top right, and click edit profile. You can change your email address there. :-) 

hope this helps. :-)

**Comment by NullVoxPopuli** [comment]
oh, I see, you already deleted it. I've perma deleted that user now. :)

**Comment by ryanadanderson** [comment]
Thanks amigo!
