### ISSUE TITLE
Naptown email is defaulted email on Attendances/new page. 

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera-todo#156]
webmaster+swingin-at-the-door@naptownstomp.org is defaulted email on registration page at: https://aeonvera.com/hosted_events/17/attendances/new

**Comment by NullVoxPopuli** [comment]
To register someone, a valid email address must be used to identify that person. The default was just put in place, because we (swingin) decided that it was too cumbersome to collect an email at the door.

This should be changed to just require a unique name.

**Comment by NullVoxPopuli** [comment]
email removed.
