### ISSUE TITLE
Organizers should be able to add people to the event

### ISSUE THREAD

**Issue by ryanadanderson** [NullVoxPopuli/aeonvera-todo#96]
The page wasn't functioning properly. There was also repeated fields: First Name, Last Name, & Name. Additionally, housing was lacking on that page. (I think)
_____
Edit:

I believe the "not functioning" issue was caused by having a duplicate email.

**Comment by NullVoxPopuli** [comment]
which page were you looking at?

**Comment by ryanadanderson** [comment]
This was in the AT THE DOOR > REGISTER button. 
I now see why housing doesn't exist here. I was thinking that organizers would be able to add a registrant to the system manually. For instance, someone emails them that they can't register for some reason, or a DJ is coming and they're lazy and haven't registered yet. They might still need to be added before the event and taken care of with housing and such. 

![image](https://cloud.githubusercontent.com/assets/10438465/5663093/3b51c69c-9710-11e4-868f-13802e36c054.png)

**Comment by NullVoxPopuli** [comment]
This is now possible!
